package konst

// CheatEnabled ...
const CheatEnabled = true

const (
	// Key0 ...
	Key0 = 0
	// Key1 ...
	Key1 = 1
	// Key2 ...
	Key2 = 2
	// Key3 ...
	Key3 = 3
	// Key4 ...
	Key4 = 4
	// Key5 ...
	Key5 = 5
	// Key6 ...
	Key6 = 6
	// Key7 ...
	Key7 = 7
	// Key8 ...
	Key8 = 8
	// Key9 ...
	Key9 = 9
	// KeyEnter ...
	KeyEnter = 13
	// KeyU ...
	KeyU = -1 // gara for now
	// KeyI ...
	KeyI = -1 // gara for now
	// KeyJ ...
	KeyJ = -1 // gara for now
	// KeyO ...
	KeyO = -1 // gara for now
	// KeyK ...
	KeyK = -1 // gara for now
	// KeyL ...
	KeyL = -1 // gara for now
	// KeyM ...
	KeyM = -1 // gara for now
	// KeySlash ...
	KeySlash = -1 // gara for now
	// KeyAsterisk ...
	KeyAsterisk = -1 // gara for now
	// KeyF10 ...
	KeyF10 = -1 // gara for now
)

// NumberInvalid ...
const NumberInvalid = -1

// FrameRate for converting tick to seconds
const FrameRate = 30

// OK ...
const OK = 1

// FakeType ...
type FakeType int

const (
	// FakeTypeNull ...
	FakeTypeNull = iota
	// FakeTypeInt ...
	FakeTypeInt
	// FakeTypeWar ...
	FakeTypeWar
	// FakeTypeChr ...
	FakeTypeChr
)

// GetFakeType ...
func GetFakeType(n int) FakeType {
	switch n {
	case int(FakeTypeNull):
		return FakeTypeNull
	case int(FakeTypeInt):
		return FakeTypeInt
	case int(FakeTypeWar):
		return FakeTypeWar
	case int(FakeTypeChr):
		return FakeTypeChr
	default:
		panic(n)
	}
}
